apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: imgproxy
  name: imgproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: imgproxy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: imgproxy
    spec:
      containers:
        - env:
            - name: IMGPROXY_BIND
              value: :5001
            - name: IMGPROXY_LOCAL_FILESYSTEM_ROOT
              value: /
            - name: IMGPROXY_USE_ETAG
              value: "true"
          image: darthsim/imgproxy:v3.11
          name: supabase-imgproxy
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/storage
              name: imgproxy-claim0
      restartPolicy: Always
      volumes:
        - name: imgproxy-claim0
          persistentVolumeClaim:
            claimName: imgproxy-claim0
status: {}
