apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: meta
  name: meta
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: meta
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: meta
    spec:
      containers:
        - env:
            - name: PG_META_DB_HOST
            - name: PG_META_DB_NAME
            - name: PG_META_DB_PASSWORD
            - name: PG_META_DB_PORT
            - name: PG_META_DB_USER
              value: supabase_admin
            - name: PG_META_PORT
              value: "8080"
          image: supabase/postgres-meta:v0.52.1
          name: supabase-meta
          resources: {}
      restartPolicy: Always
status: {}
