apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rest
  name: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rest
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: rest
    spec:
      containers:
        - env:
            - name: PGRST_DB_ANON_ROLE
              value: anon
            - name: PGRST_DB_SCHEMAS
            - name: PGRST_DB_URI
              value: postgres://authenticator:@:/
            - name: PGRST_DB_USE_LEGACY_GUCS
              value: "false"
            - name: PGRST_JWT_SECRET
          image: postgrest/postgrest:v9.0.1.20220717
          name: supabase-rest
          resources: {}
      restartPolicy: Always
status: {}
