apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: storage
  name: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: storage
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: storage
    spec:
      containers:
        - env:
            - name: ANON_KEY
            - name: DATABASE_URL
              value: postgres://supabase_storage_admin:@:/
            - name: ENABLE_IMAGE_TRANSFORMATION
              value: "true"
            - name: FILE_SIZE_LIMIT
              value: "52428800"
            - name: FILE_STORAGE_BACKEND_PATH
              value: /var/lib/storage
            - name: GLOBAL_S3_BUCKET
              value: stub
            - name: IMGPROXY_URL
              value: http://imgproxy:5001
            - name: PGRST_JWT_SECRET
            - name: POSTGREST_URL
              value: http://rest:3000
            - name: REGION
              value: stub
            - name: SERVICE_KEY
            - name: STORAGE_BACKEND
              value: file
            - name: TENANT_ID
              value: stub
          image: supabase/storage-api:v0.26.1
          name: supabase-storage
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/storage
              name: storage-claim0
      restartPolicy: Always
      volumes:
        - name: storage-claim0
          persistentVolumeClaim:
            claimName: storage-claim0
status: {}
